# https://python-markdown.github.io/extensions/admonition/

site_name: compose.mk
theme:
  features: 
    # - navigation.sections
    - navigation.expand
    # - navigation.path
    # - navigation.prune
    # - navigation.tracking
    - navigation.top
    # - toc.integrate
  logo: img/icon.png
  name: readthedocs
  custom_dir: docs/theme
  hljs_style: night-owl
  # hljs_style: github-dark
  highlightjs: true
  hljs_languages:
    - yaml
    - makefile
    - bash
    - json
  color_mode: dark
  user_color_mode_toggle: yes
  # icon:
  #   admonition:
  #     note: material/arrow-expand-down
extra_css: ["extra.css"]
site_url: https://elo-enterprises.github.io/compose.mk/
site_description: >-
  A tool / library for makefile-based automation, scripting, and lightweight orchestration.  Native support for docker, docker-compose, workflow primitives, TUI elements, and more.
remote_branch: docs
nav:
  - Overview:
    - Intro: 'overview.md'
    # - Features: 'features.md'
    - Installation: 'integration.md'
    # - 'Quick Start': 'quickstart.md'
  - Docker Compose Support: #bridge.md
    - 'Import Services from Compose': bridge.md 
    - 'Container Dispatch': container-dispatch.md
    # - 'Container Dispatch Syntax': dispatch-syntax.md
    # - 'Import Macro Arguments': macro-arguments.md
    - 'Multiple Compose Files': multiple-compose-files.md
  - Raw Docker Support: 'raw-docker.md'
  - Standard Library: 
    - 'Library Overview': standard-lib.md
    - 'Full API': api.md
  - Stand Alone Mode:
    - 'Tool Overview': tool-overview.md
    - 'Loading Compose Files': loadf.md
  - TUI Support:
    - 'TUI Overview & Gallery': embedded-tui.md
    - 'Zero-config TUIs': zero-config-tuis.md
    - 'Low-config TUIs': low-config-tuis.md
    - 'Advanced TUIs': advanced-tuis.md
    #- 'Configuration & Customization':  tui-customization-config.md
  - Misc Features:
      - 'CLI Help': cli-help.md
      - 'Supervisors & Signals': signals.md
  - Demos:
    # - 'Demos Overview': demos/overview.md
    - 'Custom Automation APIs': demos/ansible.md
    - 'Workflow Basics & Pipelining': demos/workflows.md
    # - 'Dashboarding and TUIs': demos/dashboarding.md
    - 'Platform Lifecycle Example': demos/platform.md
    - 'Polyglot Makefiles': demos/polyglots.md
    - 'Embedding Containers or Data': demos/mad-science.md
    - 'Self-extracting Executables': demos/packaging.md
  - Misc:
    - 'Design Philosophy': but-why.md 
    # - 'Configuration / Env Vars': config.md
    # - limitations.md
    # - contributing.md
    - 'Project Source': 'https://github.com/robot-wranglers/compose.mk/'
plugins:
  - search
  - autolinks 

markdown_extensions:
  - footnotes 
  - admonition
  - pymdownx.details
  - abbr
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - attr_list
docs_dir: docs
site_dir: _site
  