# https://python-markdown.github.io/extensions/admonition/

site_name: compose.mk
# repo_url: https://github.com/robot-wranglers/compose.mk
# repo_name: robot-wranglers/compose.mk
theme:
  name: readthedocs
  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.sections
    - navigation.expand
    # - navigation.path
    # - navigation.prune
    # - navigation.tracking
    - navigation.top
    - toc.integrate
  font:
    # code: Roboto Mono
    code: Rasa
  logo: img/icon.png
  custom_dir: docs/theme
  highlightjs: true
  # hljs_style: stackoverflow-dark
  # hljs_style: github-dark
  # hljs_style: a11y-dark
  hljs_style: agate
  hljs_linenums: true
  hljs_languages:
    - yaml
    - makefile
    - bash
    - json
  # color_mode: dark
  # user_color_mode_toggle: yes
  icon:
    repo: fontawesome/brands/git-alt
  # icon:
  #   admonition:
  #     note: material/arrow-expand-down
extra_css: ["extra.css"]
site_url: https://robot-wranglers.github.io/compose.mk
# site_description: >-
#   A tool / library for makefile-based automation, scripting, and lightweight orchestration.  Native support for docker, docker-compose, workflow primitives, TUI elements, and more.
remote_branch: docs
nav:
  - Overview:
    - Introduction: 'overview.md'
    # - Features: 'overview#features-design-goals'
    - Installation: 'integration.md'
  - Docker Support: #bridge.md
    - 'Import Services from Compose': bridge.md 
    - 'Dispatch Tasks in Containers': container-dispatch.md
    - 'Raw Docker Support': 'raw-docker.md'
  - Standard Library: 
    - 'Library Overview': standard-lib.md
    - 'Full API': api.md
  - Stand Alone Mode:
    - 'Tool Overview': tool-overview.md
    - 'Loading Compose Files': loadf.md
    - 'Target/Container Selector': selector.md
  - TUI Support:
    - 'TUI Overview & Gallery': embedded-tui.md
    - 'Zero-config TUIs': zero-config-tuis.md
    - 'Low-config TUIs': low-config-tuis.md
    - 'Advanced TUIs': advanced-tuis.md
    #- 'Configuration & Customization':  tui-customization-config.md
  - Misc Features:
      - 'CLI Help': cli-help.md
      - 'Stacks & Stages': stages.md
      - 'Supervisors & Signals': signals.md
      - 'Self Extracting Executables': demos/packaging.md
  - Tutorials:
    - 'Polyglot Index': demos/polyglots.md
    - 'Embedded Containers and Data': demos/matrioshka.md
    - 'Custom Automation APIs': demos/custom-automation-apis.md
    - 'Pipelining & Workflow Basics': demos/workflows.md
    - 'Platform Lifecycle Example': demos/platform.md
    - 'Notebooking & Ensembles': demos/notebooking.md
    - 'RAG Demo / Obligatory AI': demos/RAG.md
    # - 'Lean Prover': demos/notebooking.md
  - CMK Language:
      - 'Language Overview': language.md
      - 'Matrioshka Automata': matrioshka.md
      - 'Compiler & Dialects': compiler.md
      - 'Style Guide': style.md
    # - 'Theorem Proving': demos/lean.md
    # - 'Justfile Interoperability': demos/just.md
    # - 'Makeception': demos/makeception.md
  - Misc:
    - 'Design Philosophy': but-why.md 
    # - 'Configuration / Env Vars': config.md
    # - limitations.md
    # - contributing.md
    - 'Project Source': 'https://github.com/robot-wranglers/compose.mk/'
#https://github.com/mkdocs/mkdocs-redirects
plugins:
  # - search
  - autolinks
  - redirects:
      redirect_maps:
        'index.md': 'overview.md'

# https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
markdown_extensions:
  - footnotes 
  - admonition
  - pymdownx.details
  - abbr
  - def_list
  - attr_list
docs_dir: docs
site_dir: site
  