# See also: https://docs.github.com/en/actions
name: Image Testing Pipeline
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.md.j2'
      - '**.mmd'
      - '**.png'
      - '**.svg'
      - '**.gif'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.md.j2'
      - '**.mmd'
      - '**.png'
      - '**.svg'
      - '**.gif'
permissions:
  contents: read
# jobs:
#   test:
#     name: Notebook Pipeline
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Initialize
#         run: make clean init docker.system.prune
#       - name: Test Notebook Pipeline
#         run: make actions.notebook.pipeline
#       # https://til.simonwillison.net/github-actions/debug-tmate
#       - name: tmate debugging session if tests fail
#         if: failure() && github.event_name == 'workflow_dispatch'
#         uses: mxschmitt/action-tmate@v3
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Initialize
        run: make clean init 
      - name: Install chafa
        run: |
          sudo apt-get update
          sudo apt-get install -y chafa
      - name: Display test image
        run: |
          chafa docs/img/logo.png