# See also: https://docs.github.com/en/actions
name: Notebook Pipeline
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: [ "main" ]
    paths-ignore:  ['**.gif', '**.md', '**.md.j2', '**.mmd', '**.png', '**.svg']
  pull_request:
    branches: [ "main" ]
    paths-ignore:  ['**.gif', '**.md', '**.md.j2', '**.mmd', '**.png', '**.svg']
permissions:
  contents: read
jobs:
  test:
    name: Notebook Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Initialize
        run: make clean init
      - name: Run Notebook Pipeline
        run: ./demos/notebooking.mk tux.require lab.pipeline
        env:
          COLUMNS: 150
      # https://til.simonwillison.net/github-actions/debug-tmate
      # - name: tmate debugging session if tests fail
      #   if: failure() && github.event_name == 'workflow_dispatch'
      #   uses: mxschmitt/action-tmate@v3