# See also: https://docs.github.com/en/actions
name: Notebook Pipeline
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.gif'
      - '**.md'
      - '**.md.j2'
      - '**.mmd'
      - '**.png'
      - '**.svg'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.gif'
      - '**.md'
      - '**.md.j2'
      - '**.mmd'
      - '**.png'
      - '**.svg'
permissions:
  contents: read
jobs:
  test:
    name: Notebook Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        run: make clean init
      - name: Test Notebook Pipeline
        run: ./demos/notebooking.mk tux.require lab.pipeline
      # https://til.simonwillison.net/github-actions/debug-tmate
      # - name: tmate debugging session if tests fail
      #   if: failure() && github.event_name == 'workflow_dispatch'
      #   uses: mxschmitt/action-tmate@v3